export const PLAN_IDS = {
  FREE: 'FREE',
  CLASSIC: 'CLASSIC',
  PRO: 'PRO',
  ULTRA: 'ULTRA',
};

export const PLAN_DEFINITIONS = [
  {
    id: 'free',
    name: PLAN_IDS.FREE,
    price: 0,
    displayPrice: '0',
    duration: 36500,
    features: [
      '20 pesan / hari',
      'Live Call Prof Kore: 5 mnt/hari',
      'Tanpa upload file',
      'Tanpa AI Agent',
    ],
    buttonText: 'Paket Saat Ini',
    message_limit: 20,
    disabled: true,
    recommended: false,
    image_upload: false,
    file_upload: false,
    file_upload_per_window: 0,
    file_upload_window_hours: 4,
    ai_agent_level: 0,
    agent_enabled: false,
    agent_requests_per_window: 0,
    agent_window_hours: 4,
    memory_enabled: false,
    priority_access: false,
    live_call_enabled: true,
    live_call_minutes_per_window: 5,
    live_call_window_hours: 24,
  },
  {
    id: 'classic',
    name: PLAN_IDS.CLASSIC,
    price: 50000,
    displayPrice: '50.000',
    duration: 30,
    features: [
      '150 pesan / hari',
      'Upload File & Gambar: 3 file / 4 jam',
      'Live Call Prof Kore: 5 mnt / 3 jam',
      'AI Agent: 10 req / 4 jam',
    ],
    buttonText: 'Pilih Classic',
    message_limit: 150,
    disabled: false,
    recommended: false,
    image_upload: true,
    file_upload: true,
    file_upload_per_window: 3,
    file_upload_window_hours: 4,
    ai_agent_level: 1,
    agent_enabled: true,
    agent_requests_per_window: 10,
    agent_window_hours: 4,
    memory_enabled: false,
    priority_access: false,
    live_call_enabled: true,
    live_call_minutes_per_window: 5,
    live_call_window_hours: 3,
  },
  {
    id: 'pro',
    name: PLAN_IDS.PRO,
    price: 100000,
    displayPrice: '100.000',
    duration: 30,
    features: [
      '500 pesan / hari',
      'Upload File & Gambar: 10 file / 4 jam',
      'Live Call Prof Kore: 30 mnt / hari',
      'AI Agent: 50 req / 4 jam',
      'Project Memory',
    ],
    buttonText: 'Pilih Pro',
    message_limit: 500,
    disabled: false,
    recommended: true,
    image_upload: true,
    file_upload: true,
    file_upload_per_window: 10,
    file_upload_window_hours: 4,
    ai_agent_level: 2,
    agent_enabled: true,
    agent_requests_per_window: 50,
    agent_window_hours: 4,
    memory_enabled: true,
    priority_access: false,
    live_call_enabled: true,
    live_call_minutes_per_window: 30,
    live_call_window_hours: 24,
  },
  {
    id: 'ultra',
    name: PLAN_IDS.ULTRA,
    price: 200000,
    displayPrice: '200.000',
    promo: 'DISKON 70% Bulan Pertama',
    duration: 30,
    features: [
      '2000 pesan / hari',
      'Upload File Unlimited (100MB)',
      'Live Call Prof Kore: 120 mnt / hari',
      'AI Agent Unlimited',
      'Long-term Memory + Priority Access',
    ],
    buttonText: 'Pilih Ultra',
    message_limit: 2000,
    disabled: false,
    recommended: false,
    image_upload: true,
    file_upload: true,
    file_upload_per_window: -1,
    file_upload_window_hours: 24,
    ai_agent_level: 3,
    agent_enabled: true,
    agent_requests_per_window: -1,
    agent_window_hours: 24,
    memory_enabled: true,
    priority_access: true,
    live_call_enabled: true,
    live_call_minutes_per_window: 120,
    live_call_window_hours: 24,
  },
];

export const PLAN_NAMES = PLAN_DEFINITIONS.map((plan) => plan.name);

export function normalizePlanName(planName) {
  const normalized = String(planName || PLAN_IDS.FREE).trim().toUpperCase();
  return PLAN_NAMES.includes(normalized) ? normalized : PLAN_IDS.FREE;
}

export function getPlanDefinition(planName) {
  const normalized = normalizePlanName(planName);
  return PLAN_DEFINITIONS.find((plan) => plan.name === normalized) || PLAN_DEFINITIONS[0];
}

export function toPlanSeed(plan) {
  return {
    name: plan.name,
    price: plan.price,
    duration: plan.duration,
    message_limit: plan.message_limit,
    image_upload: plan.image_upload,
    file_upload: plan.file_upload,
    file_upload_per_window: plan.file_upload_per_window,
    file_upload_window_hours: plan.file_upload_window_hours,
    ai_agent_level: plan.ai_agent_level,
    agent_enabled: plan.agent_enabled,
    agent_requests_per_window: plan.agent_requests_per_window,
    agent_window_hours: plan.agent_window_hours,
    memory_enabled: plan.memory_enabled,
    priority_access: plan.priority_access,
    live_call_enabled: plan.live_call_enabled,
    live_call_minutes_per_window: plan.live_call_minutes_per_window,
    live_call_window_hours: plan.live_call_window_hours,
  };
}
